# 定义语言字典
LANGUAGES = {
    'zh': {
        'title': '批量创建文件夹',
        'save_path_label': '文件夹保存路径:',
        'select_path_button': '选择路径',
        'prefix_label': '前缀（可留空，若要使用时间，可输入 %Y-%m-%d 等时间格式。）',
        'prefix_tip_label': '帮助？',
        'suffix_label': '后缀（可留空，若要使用时间，可输入 %Y-%m-%d 等时间格式。）',
        'suffix_tip_label': '帮助？',
        'folder_name_label': '文件夹名称（一行一个文件夹，也可用“|”分割）:',
        'folder_count_label': '文件夹数量: ',
        'auto_increment_check': '启用数字自增（在文件夹名称后添加1、2、3...）',
        'submit_button': '创建文件夹',
        'time_format_tip': '时间格式说明：\n—————————————————\n%Y: 四位数的年份\n%y: 两位数的年份\n%m: 两位数的月份\n%d: 两位数的日期\n%H: 小时数(24小时制)\n%M: 分钟数\n%S: 秒数\n\n比如: \n输入%Y-%m-%d 得到2024-01-01\n输入%y-%m-%d 得到24-01-01',
        'error_invalid_prefix': "前缀 '{prefix}' 包含不支持的字符，请修改。",
        'error_invalid_suffix': "后缀 '{suffix}' 包含不支持的字符，请修改。",
        'error_invalid_folder_name': "文件夹名称 '{folder_name}' 包含不支持的字符，请修改。",
        'error_no_save_path': '请选择文件夹保存路径！',
        'error_create_folder': '创建文件夹时出现错误: {error}',
        'success_all': '所有文件夹创建成功！',
        'success_partial': '成功创建 {count} 个文件夹，部分文件夹已存在。',
        'lang_menu': '语言',
        'lang_zh': '简体中文',
        'lang_en': 'English',
        'lang_ja': '日本語',
        'lang_ko': '한국어',
        'preset_menu': '预设',
        'save_preset': '保存',
        'delete_preset': '删除',
        'preset_name': '预设名称',
        'save': '保存为预设',
        'delete': '删除',
        'preset_name_empty': '预设名称不能为空',
        'preset_not_found': '预设不存在',
        'error': '错误',
        'file_menu': '快速获取',
        'get_all_folders': '一级文件夹',
        'get_all_files': '一级文件',
        'invalid_path': '路径无效，请重新选择文件夹路径！',
        'get_all_folders_and':'所有文件夹',
        'edit_menu': '工具箱',
        'remove_duplicates': '去除重复',
        'merge_and_sort': '整理合并',
        'sort_ascending': '升序排序',
        'sort_descending': '降序排序',
        'folder_name_tip': '子文件夹创建说明：\n—————————————————————————\n1.使用 ">" 分隔父文件夹和子文件夹；\n如：一级文件夹>二级文件夹>三级文件\n\n2.每一行一个文件夹结构，也可用 "|" 分隔多个文件夹结构。\n\n3.同一个父文件夹下若要有多个子文件夹，则可以写成：\n一级文件夹>二级文件夹\n一级文件夹>二级文件夹2\n一级文件夹>二级文件夹3\n以此类推……',
        'folder_name_tip_title': '如何创建子文件夹？',
        'convert_to_structure_diagram': '转结构图',
        'get_all_folders_and_subfolders': '所有文件夹+文件',
        'error_invalid_characters': '不支持用结构图创建文件夹！',
        'help_menu': '帮助?',
        'shortcut_ctrl': 'Ctrl + Z：回撤操作\nCtrl + Y：重做操作',
        'help_shortcut':'快捷键',
        'help_admin':'软件信息',
        'admin_info':'软件版本：v3.0.0\n软件作者：破瓶子\n网址：https://www.popingzi.com/',
        'help_url': '作者主页',
        'export_menu': '表格',
        'to_excel': '导出表格',
        'from_excel': '导入表格',
        'help_excel': 'Excel表格首行直接开始，无需标题：\n第一列为一级文件夹\n第二列为二级文件夹\n第三列为三级文件夹\n……\n以此类推。',
        'excel_tip': '表格格式要求',
        'invalid_excel_format': '表格文件格式不正确',
        'empty_excel': '表格文件为空',
        'export_success': '导出成功',
        'import_success': '导入成功'
    },
    'en': {
        'title': 'Batch Create Folders',
        'save_path_label': 'Folder save path:',
        'select_path_button': 'Select Path',
        'prefix_label': 'Prefix (optional, you can use time formats like %Y-%m-%d).',
        'prefix_tip_label': 'Help?',
        'suffix_label': 'Suffix (optional, you can use time formats like %Y-%m-%d).',
        'suffix_tip_label': 'Help?',
        'folder_name_label': 'Folder names (one per line, or use "|" to separate):',
        'folder_count_label': 'Folder count: ',
        'auto_increment_check': 'Enable auto - increment (add 1, 2, 3... after folder names)',
        'submit_button': 'Create Folders',
        'time_format_tip': 'Time format description:\n—————————————————\n%Y: Four - digit year\n%y: Two - digit year\n%m: Two - digit month\n%d: Two - digit day\n%H: Hour (24 - hour format)\n%M: Minutes\n%S: Seconds\nFor example:\nEnter %Y-%m-%d to get 2024-01-01\nEnter %y-%m-%d to get 24-01-01',
        'error_invalid_prefix': "The prefix '{prefix}' contains unsupported characters. Please modify it.",
        'error_invalid_suffix': "The suffix '{suffix}' contains unsupported characters. Please modify it.",
        'error_invalid_folder_name': "The folder name '{folder_name}' contains unsupported characters. Please modify it.",
        'error_no_save_path': 'Please select a folder save path!',
        'error_create_folder': 'An error occurred while creating folders: {error}',
        'success_all': 'All folders created successfully!',
        'success_partial': '{count} folders created successfully. Some folders already exist.',
        'lang_menu': 'Language',
        'lang_zh': '简体中文',
        'lang_en': 'English',
        'lang_ja': '日本語',
        'lang_ko': '한국어',
        'preset_menu': 'Presets',
        'save_preset': 'Save as Preset',
        'delete_preset': 'Delete Preset',
        'preset_name': 'Preset Name',
        'save': 'Save',
        'delete': 'Delete',
        'preset_name_empty': 'Preset name cannot be empty',
        'preset_not_found': 'Preset not found',
        'error': 'Error',
        'file_menu': 'Quick Access',
        'get_all_folders': 'All folder names',
        'get_all_files': 'All file names',
        'error': 'Error',
        'invalid_path': 'The path is invalid. Please select a folder path again!',
        'get_all_folders_and':'All folders and subfolders',
        'edit_menu': 'Toolbox',
        'remove_duplicates': 'Remove Duplicates',
        'merge_and_sort': 'Merge and Sort',
        'sort_ascending': 'Ascending',
        'sort_descending': 'Descending',
        'folder_name_tip': 'Subfolder creation instructions:\n—————————————————————————\n1. Use ">" to separate the parent folder and subfolders.\nFor example: First-level folder>Second-level folder>Third-level folder\n\n2. One folder structure per line. You can also use "|" to separate multiple folder structures.\n\n3. If you want to have multiple subfolders under the same parent folder, you can write them as follows:\nFirst-level folder>Second-level folder\nFirst-level folder>Second-level folder 2\nFirst-level folder>Second-level folder 3\nAnd so on...',
        'folder_name_tip_title': 'How to create subfolders?',
        'convert_to_structure_diagram': 'To diagram',
        'get_all_folders_and_subfolders': 'All folders and files',
        'error_invalid_characters': 'Creating folders using the structure diagram is not supported!',
        'help_menu': 'Help?',
        'shortcut_ctrl': 'Ctrl + Z: Undo operation\nCtrl + Y: Redo operation',
        'help_shortcut': 'Shortcut keys',
        'help_admin': 'Software information',
        'admin_info': 'Software version: v3.0.0\nSoftware author: Popingzi\nWebsite: https://www.popingzi.com/',
        'help_url': 'Author\'s homepage',
        'export_menu': 'EXCEL',
        'to_excel': 'Export EXCEL',
        'from_excel': 'Import EXCEL',
        'help_excel': 'Start directly from the first row of the Excel table without a title:\nThe first column is the first-level folder.\nThe second column is the second-level folder.\nThe third column is the third-level folder.\n...\nAnd so on.',
        'excel_tip': 'Table format requirements',
        'invalid_excel_format': 'The table file format is incorrect',
        'empty_excel': 'The table file is empty',
        'export_success': 'Export successful',
        'import_success': 'Import successful'
    },
    'ja': {
        'title': 'フォルダを一括作成',
        'save_path_label': 'フォルダの保存先パス:',
        'select_path_button': 'パスを選択',
        'prefix_label': '接頭辞（空でも可、日付を使用する場合は %Y-%m-%d などの日付形式を入力）',
        'prefix_tip_label': 'ヘルプ？',
        'suffix_label': '接尾辞（空でも可、日付を使用する場合は %Y-%m-%d などの日付形式を入力）',
        'suffix_tip_label': 'ヘルプ？',
        'folder_name_label': 'フォルダ名（1行に1つのフォルダ名、または「|」で区切ることも可能）:',
        'folder_count_label': 'フォルダ数: ',
        'auto_increment_check': '自動インクリメントを有効にする（フォルダ名の後に1、2、3...を追加）',
        'submit_button': 'フォルダを作成',
        'time_format_tip': '日付形式の説明：\n—————————————————\n%Y: 西暦4桁\n%y: 西暦2桁\n%m: 月（2桁）\n%d: 日（2桁）\n%H: 時（24時間制）\n%M: 分\n%S: 秒\n例:\n%Y-%m-%d を入力すると 2024-01-01 が得られます\n%y-%m-%d を入力すると 24-01-01 が得られます',
        'error_invalid_prefix': "接頭辞 '{prefix}' にサポートされていない文字が含まれています。修正してください。",
        'error_invalid_suffix': "接尾辞 '{suffix}' にサポートされていない文字が含まれています。修正してください。",
        'error_invalid_folder_name': "フォルダ名 '{folder_name}' にサポートされていない文字が含まれています。修正してください。",
        'error_no_save_path': 'フォルダの保存先パスを選択してください！',
        'error_create_folder': 'フォルダの作成中にエラーが発生しました: {error}',
        'success_all': 'すべてのフォルダが正常に作成されました！',
        'success_partial': '{count} 個のフォルダが正常に作成されました。一部のフォルダは既に存在します。',
        'lang_menu': '言語を切り替える',
        'lang_zh': '简体中文',
        'lang_en': 'English',
        'lang_ja': '日本語',
        'lang_ko': '한국어',
        'preset_menu': 'プリセット',
        'save_preset': 'プリセットとして保存',
        'delete_preset': 'プリセットを削除',
        'preset_name': 'プリセット名',
        'save': '保存',
        'delete': '削除',
        'preset_name_empty': 'プリセット名を入力してください',
        'preset_not_found': 'プリセットが見つかりません',
        'error': 'エラー',
        'file_menu': 'クイックアクセス',
        'get_all_folders': 'すべてのフォルダ名',
        'get_all_files': 'すべてのファイル名',
        'error': 'エラー',
        'invalid_path': 'パスが無効です。フォルダパスを再選択してください！',
        'get_all_folders_and':'すべてのフォルダとサブフォルダ',
        'edit_menu': 'ツールボックス',
        'remove_duplicates': '重複を削除',
        'merge_and_sort': 'マージして並べ替える',
        'sort_ascending': '昇順',
        'sort_descending': '降順',
        'folder_name_tip': 'サブフォルダの作成方法：\n—————————————————————————\n1. 親フォルダとサブフォルダを ">" で区切ります。\n例：1階層目のフォルダ>2階層目のフォルダ>3階層目のフォルダ\n\n2. 1行に1つのフォルダ構造を記入します。複数のフォルダ構造を "|" で区切ることもできます。\n\n3. 同じ親フォルダの下に複数のサブフォルダを作成する場合は、以下のように記述します：\n1階層目のフォルダ>2階層目のフォルダ\n1階層目のフォルダ>2階層目のフォルダ2\n1階層目のフォルダ>2階層目のフォルダ3\n以下同様...',
        'folder_name_tip_title': 'サブフォルダを作成するには？',
        'convert_to_structure_diagram': '図にする',
        'get_all_folders_and_subfolders': 'すべてのフォルダとファイル',
        'error_invalid_characters': '構造図を使用したフォルダの作成はサポートされていません！',
        'help_menu': 'ヘルプ?',
        'shortcut_ctrl': 'Ctrl + Z：元に戻す操作\nCtrl + Y：やり直し操作',
        'help_shortcut': 'ショートカットキー',
        'help_admin': 'ソフトウェア情報',
        'admin_info': 'ソフトウェアバージョン：v3.0.0\nソフトウェア作者：破瓶子\nウェブサイト：https://www.popingzi.com/',
        'help_url': '作者のホームページ',
        'export_menu': 'EXCEL',
        'to_excel': '表をエクスポート',
        'from_excel': '表をインポート',
        'help_excel': 'Excel表はタイトルを必要とせず、1行目から直接始めてください：\n第1列は1階層目のフォルダです。\n第2列は2階層目のフォルダです。\n第3列は3階層目のフォルダです。\n...\n以下同様です。',
        'excel_tip': '表の形式要件',
        'invalid_excel_format': '表ファイルの形式が正しくありません',
        'empty_excel': '表ファイルが空です',
        'export_success': 'エクスポート成功',
        'import_success': 'インポート成功'
    },
    'ko': {
        'title': '폴더 일괄 생성',
        'save_path_label': '폴더 저장 경로:',
        'select_path_button': '경로 선택',
        'prefix_label': '접두사 (비워둘 수 있음, 시간을 사용하려면 %Y-%m-%d 등의 시간 형식을 입력하세요.)',
        'prefix_tip_label': '도움말?',
        'suffix_label': '접미사 (비워둘 수 있음, 시간을 사용하려면 %Y-%m-%d 등의 시간 형식을 입력하세요.)',
        'suffix_tip_label': '도움말?',
        'folder_name_label': '폴더 이름 (한 줄에 하나의 폴더 이름, 또는 "|"로 구분할 수 있음):',
        'folder_count_label': '폴더 개수: ',
        'auto_increment_check': '자동 증가 사용 (폴더 이름 뒤에 1, 2, 3... 추가)',
        'submit_button': '폴더 생성',
        'time_format_tip': '시간 형식 설명:\n—————————————————\n%Y: 4자리 연도\n%y: 2자리 연도\n%m: 2자리 월\n%d: 2자리 일\n%H: 시간 (24시간 형식)\n%M: 분\n%S: 초\n예:\n%Y-%m-%d를 입력하면 2024-01-01이 됩니다\n%y-%m-%d를 입력하면 24-01-01이 됩니다',
        'error_invalid_prefix': "접두사 '{prefix}'에 지원되지 않는 문자가 포함되어 있습니다. 수정하세요.",
        'error_invalid_suffix': "접미사 '{suffix}'에 지원되지 않는 문자가 포함되어 있습니다. 수정하세요.",
        'error_invalid_folder_name': "폴더 이름 '{folder_name}'에 지원되지 않는 문자가 포함되어 있습니다. 수정하세요.",
        'error_no_save_path': '폴더 저장 경로를 선택하세요!',
        'error_create_folder': '폴더 생성 중 오류가 발생했습니다: {error}',
        'success_all': '모든 폴더가 성공적으로 생성되었습니다!',
        'success_partial': '{count}개의 폴더가 성공적으로 생성되었습니다. 일부 폴더는 이미 존재합니다.',
        'lang_menu': '언어 전환',
        'lang_zh': '简体中文',
        'lang_en': 'English',
        'lang_ja': '日本語',
        'lang_ko': '한국어',
        'preset_menu': '사전 설정',
        'save_preset': '사전 설정으로 저장',
        'delete_preset': '사전 설정 삭제',
        'preset_name': '사전 설정 이름',
        'save': '저장',
        'delete': '삭제',
        'preset_name_empty': '사전 설정 이름은 비어 있을 수 없습니다',
        'preset_not_found': '사전 설정을 찾을 수 없습니다',
        'error': '오류',
        'file_menu': '빠른 접근',
        'get_all_folders': '모든 폴더 이름',
        'get_all_files': '모든 파일 이름',
        'error': '오류',
        'invalid_path': '경로가 유효하지 않습니다. 폴더 경로를 다시 선택하세요!',
        'get_all_folders_and':'모든 폴더 및 하위 폴더',
        'edit_menu': '도구 상자',
        'remove_duplicates': '중복 제거',
        'merge_and_sort': '병합 및 정렬',
        'sort_ascending': '오름차순',
        'sort_descending': '내림차순',
        'folder_name_tip': '하위 폴더 생성 안내:\n—————————————————————————\n1. 상위 폴더와 하위 폴더를 ">"로 구분합니다.\n예: 1단계 폴더>2단계 폴더>3단계 폴더\n\n2. 한 줄에 하나의 폴더 구조를 입력하세요. 여러 폴더 구조를 "|"로 구분할 수도 있습니다.\n\n3. 같은 상위 폴더 아래에 여러 하위 폴더를 만들려면 다음과 같이 작성할 수 있습니다:\n1단계 폴더>2단계 폴더\n1단계 폴더>2단계 폴더2\n1단계 폴더>2단계 폴더3\n이하 동일...',
        'folder_name_tip_title': '하위 폴더를 어떻게 만들까요?',
        'convert_to_structure_diagram': '도표로 만들다',
         'get_all_folders_and_subfolders': '모든 폴더 및 파일',
         'error_invalid_characters': '구조도를 사용하여 폴더를 생성할 수 없습니다!',
        'help_menu': '도움말?',
        'shortcut_ctrl': 'Ctrl + Z: 실행 취소\nCtrl + Y: 다시 실행',
        'help_shortcut': '단축키',
        'help_admin': '소프트웨어 정보',
        'admin_info': '소프트웨어 버전: v3.0.0\n소프트웨어 작성자: 파평자\n웹사이트: https://www.popingzi.com/',
        'help_url': '작성자 홈페이지',
        'export_menu': 'EXCEL',
        'to_excel': '표 내보내기',
        'from_excel': '표 가져오기',
        'help_excel': 'Excel 표는 제목 없이 첫 번째 행부터 직접 시작하세요:\n첫 번째 열은 1단계 폴더입니다.\n두 번째 열은 2단계 폴더입니다.\n세 번째 열은 3단계 폴더입니다.\n...\n이하 동일합니다.',
        'excel_tip': '표 형식 요구 사항',
        'invalid_excel_format': '표 파일 형식이 올바르지 않습니다',
        'empty_excel': '표 파일이 비어 있습니다',
        'export_success': '내보내기 성공',
        'import_success': '가져오기 성공'
    }
}